### ISSUE TITLE
Make this a package?

### ISSUE THREAD

**Issue by SiggiSmara** [wleepang/shiny-directory-input#15]
I really like this over any other solutions to selecting folders within shiny. Have you thought about making it a package in order to make it easier to use for more than one shiny app?

That way one could install once and have access to it in any and all shiny apps that require it without copying and pasting the code.

If you think this is a good idea I'm more than happy to contribute in any way.

**Comment by SiggiSmara** [comment]
I already feel that I am bombarding you with pull requests so I'm not going to generate yet another one, but I have a branch in my local repo (see here: https://github.com/SiggiSmara/shiny-directory-input/tree/package ) which is my initial attempt. You are more than welcome to take a look if you are interested.

**Comment by wleepang** [comment]
I like it!

I don't recall why I didn't do this from the beginning (possibly b/c shiny didn't support such form of extension).

Thanks for the contribution and feel free to submit a PR!

**Comment by SiggiSmara** [comment]
Cool.. I'll make a pull request but maybe after we figure out why the other pull request is behaving so strangely. Two things to consider are the name of the package, roxygen2 doesn't like using '-' in the name of the package so I changed it to camelCase. And the maintainer of the package has to have a public email if I understand it correctly. At the moment this is not a real email address.

**Comment by wleepang** [comment]
resolved in #16
