### ISSUE TITLE
UI and Server on Same script

### ISSUE THREAD

**Issue by Xavster838** [wleepang/shiny-directory-input#17]
Great Widget, I'm looking forward to using it, but have one question... 

I'm wondering if it's possible to use the shiny-directory-input without splitting the server and ui into separate scripts. I've copied the server  and ui function code from your example onto one script, and sourced the directoryInput.R on the same script, but when running am unable to get any functionality.

**Comment by Xavster838** [comment]
To elaborate, the file icon shows, but when I press the '...', no extra window pops open. I am running this on a mac.

![screen shot 2018-11-08 at 5 20 54 pm](https://user-images.githubusercontent.com/28633452/48230978-ba8b3280-e37a-11e8-8360-700904c553ca.png)

**Comment by wleepang** [comment]
I just pushed an updated version that implements this as a package.  That should make it easier to use in a single file app.  Can you give it a try?

**Comment by wleepang** [comment]
Closing since this is more than 1yr old. Reopen if still an issue.
