### ISSUE TITLE
Shiny updates caused failure

### ISSUE THREAD

**Issue by mvfki** [wleepang/shiny-directory-input#25]
Hi,

Thanks for your nice tool which has been helping me a lot! 
Recently, Shiny has updated to version 1.6.0, where there are a few changes.
In your file ["R/directoryInput.R" Line 201](https://github.com/wleepang/shiny-directory-input/blob/master/R/directoryInput.R#L201), the function/object `shiny:::%AND%` seems have been removed from the new version. Because of this, I would receive an error saying "object "`%AND%`" not found", and consequently my app cannot open. 
Though I can just downgrade Shiny back to version 1.5.0 which works fine, I guess we also need some update in `shiny-directory-input`. Otherwise, our users would suffer from this.
Appreciate for reading, and it would be really helpful if you can work on this!

Regards

**Comment by bomsterr** [comment]
I am also struggling with the same problem. I keep getting an object '%AND%' not found

**Comment by mvfki** [comment]
@bomsterr Well, I have already replaced that with another package `shinyFiles` recently. Just maybe you will need to refactor some of your code.

**Comment by bomsterr** [comment]
@mvfki sorry im not following. I used `library(shinyFiles)` and i still keep getting `object %AND% error`

**Comment by mvfki** [comment]
@bomsterr I mean in my own project, I replaced the use of shinyDirectoryInput.

**Comment by bomsterr** [comment]
what did you replace it with?

**Comment by mvfki** [comment]
`shinyFiles`, I mentioned it. 
Note that I also mentioned that you will need to refactor your code because `shinyFiles` and `shinyDirectoryInput` work differently. 
I mean: if you can't wait for the maintenance of `shinyDirectoryInput ` just don't use it and look for other options, such as `shinyFiles`
