### ISSUE TITLE
error: object '%AND%' not found

### ISSUE THREAD

**Issue by bomsterr** [wleepang/shiny-directory-input#27]
I keep getting the following error when I use `directoryInput('directory', label = 'select a directory')` in my UI:

error message: `Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
  object '%AND%' not found`

Can someone help troubleshoot? Thankyou

**Comment by wleepang** [comment]
The `shiny` package removed the `%AND%` infix operator in their 1.6.0 update. Replicated this function in `shinyDirectoryInput`.
