### ISSUE TITLE
Question on www/js folder

### ISSUE THREAD

**Issue by ldorozco** [wleepang/shiny-directory-input#4]
Hi, I have a quick question. Where on my shiny should I put the www/js folder? 

I've tried a few different locations now but the widget is still not working. The widget shows up on my shiny app, but nothing happens when I click on the ... button. 

Thank you!

Luz

**Comment by wleepang** [comment]
Hi Luz, it should be at the same level as `server.R` and `ui.R`. Also, make sure that you've sourced `directoryInput.R` at the global scope.
