### ISSUE TITLE
How to call R script function after directory input 

### ISSUE THREAD

**Issue by Marjamil** [wleepang/shiny-directory-input#5]
Hello, 

shiny-directory-input worked perfect with me, thank you so much. But what I need now is to call another r script after directory input. 

This is ReadFiles.R script. which I'd like to call. I also want 'folder' to be a directory input from ShinyApp

```
folder <- "~temp"  # path to folder that holds multiple .xls files
file_list <- list.files(path=folder, pattern="*.XLS") # create list of all .csv files in folder
#Reading multiple files into a list of data frames, 
count_genes = function(file_list){
  my_data <- lapply(file_list, read.table)
  #name the list elements to match the files
  names(my_data) <- gsub("\\.XLS$", "", file_list)
  # extract column named V2
  res = lapply(my_data, '[[', 2)
  # convert to character
  res = lapply(res, as.character)
  # make a frequency table
  res = table(unlist(res))
  write.table(res, file = "results.csv", quote = F)
  res
}
```
I was able to output res table on ShinyApp. But how can I connect all of these process, 1- Get directory as an input 2- Call ReadFiles.R 3- Output res table on ShinyApp

```
library(shiny)
source('ReadFiles.R', local = TRUE)
runApp(
  list(
    ui = fluidPage(
      
      actionButton("btn", "calculate"),
      #dataTableOutput("what")
      mainPanel(
        tableOutput('what'))
      ),
    server = function(input, output, session){
      observeEvent(input$btn, {output$what <- renderTable({count_genes(file_list)})})
    }
    
  )
)

```

**Comment by Marjamil** [comment]
@wleepang

**Comment by wleepang** [comment]
Hi @Marjamil ,

Apologies for the very delayed response - my bandwidth over the past 6mos has been rather limited.

To get the flow that you described, you need to assign your data.frame results in `res` to `output$what` in `server.R`.   This assumes that you've previously defined the function that generates the data.frame you need in the global scope of `server.R`.  See the following lines in the demo app for an example:

```
  # server.R: lines 30-33
  output$files = renderDataTable({
    files = list.files(readDirectoryInput(session, 'directory'), full.names = T)
    data.frame(name = basename(files), file.info(files))
  })
```

Hope this helps.
