### ISSUE TITLE
Gtkdialog mapped without a transient parent

### ISSUE THREAD

**Issue by kkahrizi** [wleepang/shiny-directory-input#6]
I got this to work. Great widget! FYI: I noticed the fix for the zenity bug "Gtkdialog mapped without a transient parent." checks if path list length is equal to 2. Running Ubuntu 16.04.3, the list length is equal to 4, and the last element is the path (breaking current code). Perhaps the code should be written to be agnostic to list length and always select the last element in the event of a list being passed to path.

**Comment by wleepang** [comment]
Thanks for the the input, and would gladly accept a pull request.

**Comment by wleepang** [comment]
fixed in PR #14
