### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by elinw** [wleepang/shiny-directory-input#7]
Hi,

I'd love to use this in my app which will be part of a package submitted to CRAN, but there is no license.  
Do you have a license in mind?  Or would you like to be a contributor to our project https://github.com/ropenscilabs/qcoder  which is GPL-3?   You'd be very welcome to send a pull request if that is what you prefer.  Our Shiny apps are in the inst/apps folder.

**Comment by wleepang** [comment]
Hi @elinw ,

I've added a BSD-3 license to the repository, which should be compatible with GPL-3.  I'm happy to contribute if you need extra hands.

**Comment by elinw** [comment]
Thanks!
